user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;

    keepalive_timeout  65;

    # voir troubleshooting.md #40 - limit_req_zone doit etre au niveau http, d'ou ce nginx.conf custom
    # (sinon nginx.conf par defaut de l'image). limit_req applique dans conf.d/default.conf, zone ici.
    limit_req_zone $binary_remote_addr zone=login_zone:10m rate=5r/m;

    include /etc/nginx/conf.d/*.conf;
}
